package model

func GetQuotesData(dayNight int) []string {
	kehidupanQuotes := []string{
		"Hal yang paling penting adalah menikmati hidupmu, menjadi bahagia, apapun yang terjadi.",
		"Hidup itu sederhana, kita yang membuatnya sulit.",
		"Hidup itu bukan soal menemukan diri Anda sendiri, hidup itu membuat diri Anda sendiri.",
		"Hidup adalah mimpi bagi mereka yang bijaksana, permainan bagi mereka yang bodoh, komedi bagi mereka yang kaya, dan tragedi bagi mereka yang miskin.",
		"Kenyataannya, ada tidak tahu apa yang akan terjadi besok. Hidup adalah pengendaraan yang gila dan tidak ada yang menjaminnya.",
		"Tujuan hidup kita adalah menjadi bahagia.",
		"Hidup yang baik adalah hidup yang diinspirasi oleh cinta dan dipandu oleh ilmu pengetahuan.",
		"Hidup adalah serangkaian perubahan yang alami dan spontan. Jangan tolak mereka karena itu hanya membuat penyesalan dan duka. Biarkan realita menjadi realita. Biarkan sesuatu mengalir dengan alami ke manapun mereka suka.",
		"Anda di sini hanya untuk persinggahan yang singkat. Jangan terburu, jangan khawatir. Yakinlah bahwa Anda menghirup wangi bunga sepanjang perjalanan.",
		"Hidup adalah cermin dan akan merefleksikan kembali kepada para pemikir mengenai apa yang mereka pikirkan.",
		"Saya memiliki filosofi yang sederhana: isi apa yang kosong, kosongkan apa yang terlalu penuh.",
		"Kehidupan adalah 10 persen apa yang terjadi pada Anda dan 90 persen adalah bagaimana Anda meresponnya",
		"Satu-satunya keterbatasan dalam hidup adalah perilaku yang buruk.",
		"Seseorang yang berani membuang satu jam waktunya tidak mengetahui nilai dari kehidupan.",
		"Apa yang kita pikirkan menentukan apa yang akan terjadi pada kita. Jadi jika kita ingin mengubah hidup kita, kita perlu sedikit mengubah pikiran kita.",
		"Ia yang mengerjakan lebih dari apa yang dibayar pada suatu saat akan dibayar lebih dari apa yang ia kerjakan",
		"Satu-satunya sumber pengetahuan adalah pengalaman",
		"Saya selalu mencoba untuk mengubah kemalangan menjadi kesempatan",
		"Perjalanan 1000 mil dimulai dengan satu langkah kaki",
		"Seseorang yang pernah melakukan kesalahan dan tidak pernah memperbaikinya berarti Ia telah melakukan satu kesalahan lagi.",
		"Beberapa orang memimpikan kesuksesannya, sementara yang lainnya bangun setiap pagi untuk mewujudkan mimpinya",
		"Tidak ada perjuangan yang dilakukan tanpa rasa sakit, namun Anda harus percaya bahwa rasa sakit itu hanya sesaat saja dan akan diganti dengan kebahagiaan",
		"Anda seringkali lupa terhadap apa saja yang sudah dimiliki, tetapi selalu mengingat apa yang dimiliki orang lain",
		"Anda tidak akan pernah belajar sabar dan berani jika di dunia ini hanya ada kebahagiaan",
		"Maafkanlah sikap Anda ketika mengalami kegagalan dalam meraih mimpi dan percayalah akan ada mimpi lain yang lebih besar dan lebih baik dari mimpi Anda yang sudah dirancang sebelumnya",
		"Masa depan adalah milik Anda yang telah menyiapkannya dari hari ini",
		"Sekecil apapun nominalnya, uang akan cukup jika digunakan untuk HIDUP. Namun, sebesar apapun nominalnya, uang tidak akan pernah cukup jika digunakan untuk memenuhi GAYA HIDUP",
		"Kesabaran adalah obat terbaik untuk segala kesulitan",
		"Kedewasaan tidak dilihat dari usia, tetapi dilihat dari sikap dan tingkah laku",
		"Percaya diri adalah rahasia nomor satu dari kesuksesan",
		"Jika kapal Anda tidak kunjung datang maka berenanglah",
		"Kemanapun Anda pergi, lakukanlah segalanya dengan segenap hati.",
		"Bertambahnya usia bukan berarti kita memahami segalanya",
		"Keraguan membunuh lebih banyak harapan daripada kegagalan",
		"Siapapun bisa jadi apapun!",
		"Kata-kata Anda menunjukkan kualitas diri Anda",
		"Hati memiliki nalarnya sendiri, tetapi nalar tidak memiliki hati",
		"Majulah tanpa menyingkirkan orang lain. Naiklah tanpa menjatuhkan orang lain",
		"Pamer adalah ide yang bodoh untuk sebuah kemenangan",
		"Jika hanya mencari kesempurnaan, maka Anda tidak akan pernah tenang",
		"Hanya Saya yang dapat mengubah hidup Saya, tidak ada orang lain yang bisa melakukannya untuk Saya",
		"Bersyukurlah atas semua hal yang dimiliki sekarang karena Anda tidak pernah tahu kapan akan kehilangannya",
		"Hidup itu bukan tentang memiliki dan mendapatkan, tetapi tentang memberi serta menjadi \"sesuatu\"",
		"Jangan takut jika Anda berjalan lambat, takutlah jika hanya berdiam",
		"Terkadang Anda diuji bukan untuk menunjukkan kelemahan yang dimiliki, tetapi diuji untuk menemukan kekuatan yang ada di dalam diri",
		"Kita sibuk mencari yang sempurna, sampai-sampai melewatkan yang siap menerima apa adanya",
		"Beri nilai dari usahanya, bukan dari hasilnya. Baru Anda bisa menilai kehidupan",
	}

	bedtimeQuotes := []string{
		"Selamat malam, biarkan tidurmu menjadi pelukan nyaman dari kelelahan hari ini.",
		"Malam ini, biarkan pikiranmu pergi bersama angin sepoi-sepoi. Selamat tidur!",
		"Setiap bintang di langit memiliki cerita indah, dan malam ini, biarkan mimpi-mimpi membawamu ke kisahmu sendiri. Selamat malam!",
		"Hari yang sibuk sudah berlalu, saatnya untuk memulihkan tenaga. Selamat malam dan tidur yang nyenyak!",
		"Ketika kamu melihat langit malam, ingatlah bahwa setiap bintang adalah harapan baru. Selamat tidur dan bangunlah dengan semangat yang baru!",
		"Biarkan lembutnya malam ini merangkulmu. Selamat malam dan nikmatilah perjalananmu ke dunia mimpi.",
		"Malam ini, biarkan hatimu ringan seperti embun di pagi hari. Selamat tidur!",
		"Dalam ketenangan malam, temukan kedamaian dan ketenangan. Selamat malam dan mimpi indah!",
		"Tidurlah dengan keyakinan bahwa besok adalah hari yang lebih baik. Selamat malam dan istirahat yang nyenyak!",
		"Seiring dengan bintang-bintang, biarkan perasaan syukur memenuhi hatimu sebelum tidur. Selamat malam!",
		"Malam ini, hembuskan napasmu dengan lega dan biarkan pikiranmu terbang bebas. Selamat tidur dan mimpi manis!",
		"Sebelum kamu terlelap, hitunglah berkah dan momen-momen indah hari ini. Selamat malam dan tidur yang nyaman!",
		"Malam ini, percayalah bahwa besok akan membawa kebahagiaan baru. Selamat tidur dan semoga esok lebih cerah!",
		"Di bawah langit yang gelap, biarkan pikiranmu menemukan ketenangan. Selamat malam dan istirahat yang baik!",
		"Tidurlah dengan damai, dan semoga pagi membawa sinar matahari dan kebahagiaan yang tak terhitung. Selamat malam!",
		"Jangan biarkan pikiranmu terlalu serius, malam ini hanya untuk bersantai. Selamat tidur dan mimpi indah!",
		"Malam ini, biarkan pelukannya menghapus semua kekhawatiran. Selamat malam dan istirahat yang tenang!",
		"Saat kamu menutup mata, biarkan semua pikiran yang tidak perlu pergi. Selamat tidur dan mimpi yang damai!",
		"Hari ini mungkin sulit, tetapi besok membawa harapan baru. Selamat malam dan persiapkan dirimu untuk petualangan baru!",
		"Malam ini, anggaplah tidurmu sebagai perjalanan ke dunia yang penuh keajaiban. Selamat tidur!",
		"Biarkan malam ini menjadi pelukan lembut yang mengantar kamu ke mimpi-mimpi yang menyenangkan. Selamat malam!",
		"Tidurlah dengan damai, dan ketika kamu bangun, semoga hatimu penuh dengan energi positif. Selamat malam!",
		"Setiap tidur adalah kesempatan untuk memulai kembali. Selamat malam dan semoga kamu mendapatkan istirahat yang nyaman!",
		"Selamat malam, waktu untuk beristirahat. Biarkan mimpi indah membawa Anda ke dunia khayalan yang penuh kedamaian.",
		"Di ujung hari ini, renungkanlah kebahagiaan dan keberuntungan yang telah Anda temui. Selamat malam!",
		"Jangan biarkan khawatir menghampiri tidurmu. Biarkan pikiranmu bersantai dan beristirahat. Selamat malam!",
		"Setiap malam adalah kesempatan untuk menyegarkan kembali pikiran dan tubuh. Selamat malam dan tidur nyenyak!",
		"Besok adalah halaman baru. Selesaikan hari ini dengan hati yang ringan dan persiapkan diri untuk petualangan baru esok hari. Selamat malam!",
		"Jangan biarkan stres hari ini menjadi beban untuk tidurmu. Biarkan semua pikiran negatif pergi dan nikmatilah tidurmu. Selamat malam!",
		"Tidurlah dengan damai dan bangun dengan semangat yang baru. Mimpi manis!",
		"Sebelum mata ini terpejam, ingatlah semua kebaikan dalam hidupmu. Selamat malam dan beristirahatlah dengan nyenyak!",
		"Hari ini mungkin tidak sempurna, tapi besok adalah kesempatan baru. Selamat malam, nikmati istirahatmu!",
		"Jangan biarkan masalah menghampiri tidurmu. Biarkan mereka menunggu di luar pintu sampai esok hari. Selamat malam!",
		"Tidur adalah obat terbaik. Semoga Anda mendapatkan dosis yang cukup malam ini. Selamat malam!",
		"Peluk erat mimpi-mimpi indahmu dan biarkan mereka membawa senyum ke wajahmu besok pagi. Selamat malam!",
		"Hari yang melelahkan telah berlalu. Tidurlah dengan nyaman dan bangun dengan semangat yang baru. Selamat malam!",
		"Setiap tidur adalah kesempatan untuk memulai kembali. Nikmati perjalananmu ke dunia mimpi. Selamat malam!",
		"Biarkan malam membawa ketenangan ke hatimu dan sukacita ke esokan harimu. Selamat malam!",
		"Terima kasih untuk hari yang luar biasa. Sekarang, beristirahatlah dan siapkan dirimu untuk hari yang lebih indah besok. Selamat malam!",
		"Jika bintang-bintang dapat menceritakan cerita, mereka akan memberimu kisah indah sepanjang malam. Selamat malam!",
		"Tidurlah dengan tenang dan bangun dengan semangat yang baru. Selamat malam!",
		"Hari yang indah telah berlalu. Tidurlah dengan damai dan persiapkan dirimu untuk hari yang lebih baik. Selamat malam!",
		"Saat kamu menutup mata, biarkan semua pikiran negatif pergi. Tidurlah dengan tenang dan nikmatilah istirahatmu. Selamat malam!",
		"Besok adalah babak baru dalam petualangan hidupmu. Selamat malam dan rilekslah untuk perjalanan yang akan datang!",
	}
	if dayNight == 1 {
		return kehidupanQuotes
	}
	return bedtimeQuotes
}
